### PR TITLE
Fix formatting

### PR DESCRIPTION
**Pull request by charlienewey**
Some of the SVG elements for the visualisations are injected into the HTML after the page is loaded, which sort of screws up formatting. It should be fixed with this patch.

### CODE REVIEW

**Comment by charlienewey** [comment]
Also added some extra charts

**Review by andreaseliasson — APPROVED** [review]
Not sure of how to test this by checking out a branch (I can only fetch the `wip_charlie` branch), but the code looks good :)

**Comment by andreaseliasson** [comment]
I assume it's safe to merge?

**Comment by charlienewey** [comment]
Safe to merge!

**Pull request merged**
